name: 'semaphore render'

on:
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request:
    branches: ["master"]

jobs:
  render:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: sudo apt-get install -y inkscape inkscape-open-symbols ninja-build
      - name: Render
        run: |
          mkdir -p build && cd build
          cmake .. -GNinja -DWITH_LIVEKIT_VARIANT=ON -DCMAKE_INSTALL_PREFIX=/usr
          ninja
          DESTDIR="$PWD"/dist ninja install
      - name: Pack
        run: |
          mkdir -p artifacts
          ARTIFACT_DIR="$(readlink -f artifacts)"
          pushd "$PWD"/build/dist/usr/share/plymouth/themes/
          tar cJf "${ARTIFACT_DIR}"/semaphore.tar.xz semaphore
          tar cJf "${ARTIFACT_DIR}"/semaphore-livekit.tar.xz livekit
          popd
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: rendered
          path: artifacts
